server:
  AppVersion: 0.1
  Port: 8080
  PprofPort: 5558
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 5
  Debug: true

mongodb:
  User: root
  Password: root

linebot:
  ChannelSecret: "6df4970b1d94af5edf5a7a0c8a349a50"
  ChannelAccessToken: "OEC6ojwzDWuY0d2p4Rblah+YnhEA0iAYPDZ+5tRvHsKvdYSXqfZkj0mFjwsayQJx9xFq6XT0bxgrfxad9RlK5f3dnawESgs8aEkvfihnNQfCHcbDN3JrJJtVAPVPk6qJsAoV7BZawt/adVBdt4/ueAdB04t89/1O/w1cDnyilFU="

logger:
  Development: true
  DisableCaller: false
  Encoding: json
  Level: info
  EnableFile: false
  InfoFileName: "./logs/server.log"
  MaxBackups: 5
  MaxAge: 30
  MaxSize: 1
